### ISSUE TITLE
Crash on sleeping past 6th day

### ISSUE THREAD

**Issue by Edward-Knight** [DavyK/cultivate#122]
```Traceback (most recent call last):
  File "/Users/eknight/pyweek27/cultivate/.venv/bin/cultivate", line 11, in <module>
    load_entry_point('cultivate', 'gui_scripts', 'cultivate')()
  File "/Users/eknight/pyweek27/cultivate/cultivate/main.py", line 57, in main
    handle_event(event, player, game_map, inventory, static_interactables, pickups)
  File "/Users/eknight/pyweek27/cultivate/cultivate/main.py", line 201, in handle_event
    player.start_interact()
  File "/Users/eknight/pyweek27/cultivate/cultivate/player.py", line 129, in start_interact
    if self.game_state.is_day_done():
  File "/Users/eknight/pyweek27/cultivate/cultivate/game_state.py", line 85, in is_day_done
    return self.task_status[self.day].completed or self.task_status[self.day].sabotaged
IndexError: list index out of range```

**Comment by Edward-Knight** [comment]
This is just a result of us not having an ending
